pyenv:
  versions:
    - "2.7.15"
    - "3.7.2"
    - "anaconda3-5.3.1"
  
  virtualenvs:
    - name: "jupyter3"
      py_version: "3.7.2"
    
    - name: "tools3"
      py_version: "3.7.2"

    - name: "ipython2"
      py_version: "2.7.15"

    - name: "tools2"
      py_version: "2.7.15"
  
  venv_packages:
    - virtualenv: jupyter3
      packages: jupyter
      setup_ipykernel: true
    
    - virtualenv: ipython2
      packages: ipykernel
      setup_ipykernel: true
    
    - virtualenv: tools3
      packages: youtube-dl rows click requests requests_cache tqdm
    
    - virtualenv: tools2
      packages: rename s3cmd fabric mercurial