---
- name: Install Visual Studio Code
  homebrew_cask:
    name: visual-studio-code
    state: present

- name: Install Chrome
  homebrew_cask:
    name: google-chrome
    state: present

- name: Install Iterm 2
  homebrew_cask:
    name: iterm2
    state: present